package com.easemob.live.cdn.presenter;

public abstract class CdnTokenPresenter extends CdnBasePresenter {
    /**
     * Through the relevant information of the ring letter, in exchange for the token of agora
     *
     * @param hxId     ring letter id
     * @param channel  channel
     * @param hxAppkey ring letter appkey
     * @param uid      The uid required by agora, used to identify the user, the suggestion is related to the ring letter id, which is generated by the user
     * @param isRenew  whether to update the Token operation
     */
    public abstract void getFastToken(String hxId, String channel, String hxAppkey, int uid, boolean isRenew);

    public abstract void getCdnUrl(String channel);
}
